version: '2.1'
jobs:
    build:
        docker:
            - image: circleci/node:14.17.6
            
        working_directory: ~/repo
        
        steps:
          - run: npm install
          - run: npm test
